FROM golang:1.24.5 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -mod=vendor -o ./backend ./cmd/...

FROM scratch AS final
COPY --from=builder /app/backend /backend
EXPOSE "8000"
ENTRYPOINT ["/backend"]
