FROM golang:1.25.1-alpine3.22 AS build

WORKDIR /app
COPY . .

RUN go mod tidy
RUN go build -o ./build/executable/app ./cmd/main.go

FROM alpine:3.22

WORKDIR /app

COPY --from=build /app/build/executable/app ./app

EXPOSE 7000

CMD ["/app/app"]